/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConversationId = IDL.Nat;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ConversationSummary = IDL.Record({
  'id' : ConversationId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'messageCount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createConversation' : IDL.Func([IDL.Text], [ConversationId], []),
  'deleteConversation' : IDL.Func([ConversationId], [], []),
  'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'getWelcomeSuggestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'makeAIRequest' : IDL.Func([IDL.Text], [IDL.Text], []),
  'renameConversation' : IDL.Func([ConversationId, IDL.Text], [], []),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConversationId = IDL.Nat;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ConversationSummary = IDL.Record({
    'id' : ConversationId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'messageCount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createConversation' : IDL.Func([IDL.Text], [ConversationId], []),
    'deleteConversation' : IDL.Func([ConversationId], [], []),
    'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'getWelcomeSuggestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'makeAIRequest' : IDL.Func([IDL.Text], [IDL.Text], []),
    'renameConversation' : IDL.Func([ConversationId, IDL.Text], [], []),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };